[WIP] Port R docs vignettes to epidatpy
cmu-delphi/epidatpy pull request #40
Opened 2024-08-16 14:05 UTC by rzats

Specifically [this one](https://github.com/cmu-delphi/epidatr/blob/dev/vignettes/epidatr.Rmd).

2024-08-16 14:06 UTC, rzats commented on Makefile
> +doc:
Can't be `docs` because we have a directory named `docs` :) (the other one is just renamed for consistency)

2024-08-16 14:07 UTC, rzats commented on epidatpy/_covidcast.py
> +        EpidataFieldInfo("sample_size", EpidataFieldType.text),
Without this change the second query of `docs_smoke_test` fails, because in the dataset there's a sample size of `O` (the letter O, not zero).

2024-08-16 14:08 UTC, rzats commented on docs_smoke_test.py
> +from epidatpy import CovidcastEpidata, EpiDataContext, EpiRange
This file is just to generate the code outputs for the docs, it can be deleted before merging.

Alternatively, do we wanna add a Sphinx plugin that automatically evaluates the code in the docs?

2024-08-29 01:48 UTC, dshemetov requested changes
Thanks Rostyslav, this looks great. I made a few requests to fix a few examples, but overall this is excellent. We might just need to let `sample_size` be type `text` for now (wow). A better getting_started plot would be good (request in a comment) and a simple plot for revisions would be good (request in a comment). Everything else is looking great though. 

A few more things: 
- please remove the old unfinished docs: `signals_covid.rst` and `covidcast_examples.rst`
- move the `epidatpy` reference section below the intro guides in the left bar
- the [signal-discovery page](https://cmu-delphi.github.io/epidatr/articles/signal-discovery.html) in epidatr has a table of available endpoints that combines the table we have right now in `epidatpy.rst`... I would like to combine those somehow; could you write a simple `available_endpoints()` function that pretty prints a table similar to what is there in R and use that function to produce a table in `signal_discovery.rst`? Once that's done, I think we'll be able to just remove `epidatpy.rst`.

2024-08-29 01:48 UTC, dshemetov commented on docs/getting_started_with_epidatpy.rst
> +We can fetch a subset of states by listing out the desired locations:
todo: the wording and examples here are weird. could you please make a change that brings it up to parity with the change I'm making to epidatr [here](https://github.com/cmu-delphi/epidatr/pull/292)?

2024-08-29 01:48 UTC, dshemetov commented on docs/getting_started_with_epidatpy.rst
> +>>> data.plot(x="time_value", y="value", title="Smoothed CLI from Facebook Survey", xlabel="Date", ylabel="CLI")
This looks pretty good, but let's change this to a plot of multiple lines, one for each of pa, ca, and fl. Hopefully the scale is comparable (otherwise we might need to choose a normalized signal).

2024-08-29 01:48 UTC, dshemetov commented on docs/signal_discovery.rst
> +- ``dua`` - Link to the Data Use Agreement.
fix: could you update the columns listed? They don't match the dataframe above.

2024-08-29 01:48 UTC, dshemetov commented on docs/signal_discovery.rst
> +- ``signal`` - Signal name.
```suggestion
- ``signal`` - API-internal signal name.
```

2024-08-29 01:48 UTC, dshemetov commented on docs/signal_discovery.rst
> +- ``name`` - Name of signal.
```suggestion
- ``name`` - Human-readable signal name.
```

2024-08-29 01:48 UTC, dshemetov commented on docs/getting_started_with_epidatpy.rst
> +>>> data.plot(x="time_value", y="value", title="Smoothed CLI from Facebook Survey", xlabel="Date", ylabel="CLI")
Also in the versioned_data.rst, it would be nice to have a plot that demonstrates data revisions where a time series as_of an older versioned is plotted against a more up to date snapshot. There are some plots that demonstrate this in [epipredict vignettes](https://cmu-delphi.github.io/epipredict/articles/sliding.html) (though they do it in the context of forecasting). We don't need to do anything quite so fancy, you just might be able to use the signals used there to generate a simpler plot.

2024-08-29 01:48 UTC, dshemetov commented on docs_smoke_test.py
> +from epidatpy import CovidcastEpidata, EpiDataContext, EpiRange
That Sphinx plugin sounds handy, sure!

2024-08-29 01:48 UTC, dshemetov commented on epidatpy/_covidcast.py
> +        EpidataFieldInfo("sample_size", EpidataFieldType.text),
😱 

Could you isolate that row and make an issue about it in delphi-epidata? We definitely need to fix it in the database (and where-ever in acquisition that this occurred).

2024-09-10 13:47 UTC, rzats commented on docs_smoke_test.py
> +from epidatpy import CovidcastEpidata, EpiDataContext, EpiRange
I remade that part of the docs to use [`sphinx-exec-directive`](https://github.com/yongrenjie/sphinx-exec-directive), a plugin which dynamically evaluates code blocks.

It supports Jupyter-style context, so boilerplate - like imports and the `EpidataContext` declaration - only has to be repeated once.

Visualizations are still kept in this Python file though, as those cannot be dynamically rendered inline.

2024-09-10 15:27 UTC, rzats commented on docs/getting_started_with_epidatpy.rst
> +>>> data.plot(x="time_value", y="value", title="Smoothed CLI from Facebook Survey", xlabel="Date", ylabel="CLI")
Added both of these :)

2024-09-10 17:22 UTC, rzats commented
@dshemetov finished updating the, please take a look again!

One thing that's still a WIP:

> the [signal-discovery page](https://cmu-delphi.github.io/epidatr/articles/signal-discovery.html) in epidatr has a table of available endpoints that produces a table like what is now in getting_started.rst... I would like to combine those; could you write a simple available_endpoints() function that pretty prints a table similar to what is there in R and use that function to produce a table in signal_discovery.rst?

Here I used a somewhat similar approach to R, but a bit more complex as Python doesn't have a nice native "table" format. 

My solution instead is to:
- grab all methods that start with `pub_` or `pvt_` from `AEpiDataEndpoints`;
- get their docstrings;
- combine the methods and the docstrings into a CSV file. I updated `make doc` so this file is regenerated before the docs;
- display this CSV file as a pretty-printed table in the signal discovery doc.

Let me know if this approach is OK, and I can clean up the docstrings themselves. Currently they have a couple of missing values and inconsistent formatting, and don't specify links to the original endpoints either.

2024-09-10 18:16 UTC, dshemetov commented on docs_smoke_test.py
> +from epidatpy import CovidcastEpidata, EpiDataContext, EpiRange
Do you trust that plugin? The user's profile is private and it only has 3 stars. Is it recommended by the sphinx community elsewhere? I skimmed the source and nothing was suspicious, but it has the power to run arbitrary code on your system, so I'm a bit wary.

2024-09-10 18:21 UTC, dshemetov commented on docs_smoke_test.py
> +from epidatpy import CovidcastEpidata, EpiDataContext, EpiRange
I wonder if directly writing Jupyter notebooks is an easier way to go about this? https://github.com/spatialaudio/nbsphinx/

2024-09-10 18:25 UTC, dshemetov commented
From a comment above: maybe a lot of the work here can be simplified by using Jupyter notebooks directly using https://github.com/spatialaudio/nbsphinx/. Pandas offers quite a lot of configuration options for how to print its tables, [see here](https://pandas.pydata.org/docs/user_guide/style.html), maybe you could use that and `available_endpoints()`?

2024-10-02 22:46 UTC, dshemetov approved these changes
This looks great, thanks for setting this all up Rostyslav! I took another pass through all the documentation, made sure all the language flows, and that we we covered all the major features (like caching and signal discovery).

2024-10-02 22:46 UTC, merged